config/routes.rb
Rails.application.routes.draw do
  resources :task_items
  resources :kadais
  root 'task_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kadai.rb
class Kadai < ApplicationRecord
end

app/models/task_item.rb
class TaskItem < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kadais_controller.rb
class KadaisController < ApplicationController
  before_action :set_kadai, only: [:show, :edit, :update, :destroy]

  # GET /kadais
  def index
    @kadais = Kadai.all
  end

  # GET /kadais/1
  def show
  end

  # GET /kadais/new
  def new
    @kadai = Kadai.new
  end

  # GET /kadais/1/edit
  def edit
  end

  # POST /kadais
  def create
    if @kadai = Kadai.create(kadai_params)
        redirect_to @kadai, notice: 'タスクを作成しました'
       else
        render :new
    end
  end

  # PATCH/PUT /kadais/1
  def update
      if @kadai.update(kadai_params)
        redirect_to @kadai, notice: 'タスクを更新しました'
      else
        render :edit
      end
  end

  # DELETE /kadais/1
  def destroy
    @kadai.destroy
      redirect_to kadais_url, notice: 'タスクを削除しました'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kadai
      @kadai = Kadai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kadai_params
      params.require(:kadai).permit(:title, :body)
    end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController
  before_action :set_task_item, only: [:show, :edit, :update, :destroy]

  def index
    @task_items = TaskItem.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @task_item = TaskItem.new
  end

  def edit
  end

  def create
    @task_item = TaskItem.new(task_item_params)
    if @task_item.save
      redirect_to @task_item, notice: 'Task item was successfully created.'
    else
      render :new
    end
  end

  def update
      if @task_item.update(task_item_params)
        redirect_to @task_item, notice: 'Task item was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @task_item.destroy
      redirect_to task_items_url, notice: 'Task item was successfully destroyed.'
      head :no_content
    end
  end

  private
  
    def set_task_item
      @task_item = TaskItem.find(params[:id])
    end

    def task_item_params
      params.require(:task_item).permit(:title, :body)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kadais_helper.rb
module KadaisHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/kadais/_form.html.slim
= form_for @kadai do |f|
  - if @kadai.errors.any?
    #error_explanation
      h2 = "#{pluralize(@kadai.errors.count, "error")} prohibited this kadai from being saved:"
      ul
        - @kadai.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/kadais/edit.html.slim
h1 タスク編集

== render 'form'

=> link_to '詳細', @kadai
'|
=< link_to '一覧に戻る', kadais_path

app/views/kadais/index.html.slim
h1 タスク一覧

table
  thead
    tr
      th ID
      th タイトル
      th 本文
      th 作成日時
      th 更新日時

  tbody
    - @kadais.each do |kadai|
      tr
        td = kadai.id
        td = kadai.title
        td = kadai.body
        td = kadai.created_at
        td = kadai.updated_at      
        td = link_to '詳細', kadai
        td = link_to '編集', edit_kadai_path(kadai)
        td = link_to '削除', kadai, data: { confirm: '本当に削除しますか？' }, method: :delete

br

= link_to '新規作成', new_kadai_path

app/views/kadais/new.html.slim
h1 新規タスク

== render 'form'

= link_to '一覧に戻る', kadais_path

app/views/kadais/show.html.slim
h1 タスク詳細

== render 'form'

p#notice = notice

p
  strong Title:
  = @kadai.title
p
  strong Body:
  = @kadai.body

=> link_to '編集', edit_kadai_path(@kadai)
'|
=< link_to '一覧に戻る', kadais_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Task
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/task_items/_form.html.slim
= form_for @task_item do |f|
  - if @task_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task_item.errors.count, "error")} prohibited this task_item from being saved:"
      ul
        - @task_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/task_items/edit.html.slim
h1 Editing task_item

== render 'form'

=> link_to 'Show', @task_item
'|
=< link_to 'Back', task_items_path

app/views/task_items/index.html.slim
h1 Listing task_items

table
  thead
    tr
      th Title
      th Body
      th
      th
      th

  tbody
    - @task_items.each do |task_item|
      tr
        td = task_item.title
        td = task_item.body
        td = link_to 'Show', task_item
        td = link_to 'Edit', edit_task_item_path(task_item)
        td = link_to 'Destroy', task_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Task item', new_task_item_path

app/views/task_items/new.html.slim
h1 New task_item

== render 'form'

= link_to 'Back', task_items_path

app/views/task_items/show.html.slim
p#notice = notice

p
  strong Title:
  = @task_item.title
p
  strong Body:
  = @task_item.body

=> link_to 'Edit', edit_task_item_path(@task_item)
'|
=< link_to 'Back', task_items_path